name: Build and Deploy Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: xsouzax/meusite-bootcamp-devops
  IMAGE_TAG: 1.0

jobs:
  verify-secrets:
    name: Verify Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Secrets
        run: |
          echo "Docker Hub user: ${{ secrets.DOCKER_HUB_USERNAME }}"
          echo "Docker Hub Token (3 primeiros chars): ${{secrets.DOCKER_HUB_TOKEN }}"

  build:
    name: Build Docker Image
    needs: verify-secrets  # Executa apenas após verificar as secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy to AWS
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to ECS/EC2
        run: |
          echo "Deploying ${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG }} to AWS"
          # Exemplo para ECS:
          # aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment